### ISSUE TITLE
crashed when using Cesium official package

### ISSUE THREAD

**Issue by zouyaoji** [RaymanNg/3D-Wind-Field#1]
Hello, this is a good example. Have you modified the source code of Cesium? Because I use the Cesium official package to report an error. Is there a way to implement the wind map with the official package?

**Comment by zouyaoji** [comment]
“modify Cesium source code to enable MRT support in ComputeCommand”.
What is MRT?  ^_^

**Comment by RaymanNg** [comment]
MRT is Multiple Render Target, you can check [this MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_draw_buffers) for more info

It is strange that MRT is supported in DrawCommand but not in ComputeCommand, I have opened a [thread for that in the Cesium Forum](https://groups.google.com/forum/#!searchin/cesium-dev/mrt%7Csort:date/cesium-dev/sVgkoLsM9Lk/i2ra0k6gCgAJ)

If you want to use this wind map with the official package, replace all the ComputeCommands with corresponding DrawCommands in the [customParticleSystem.js](https://github.com/RaymanNg/3D-Wind-Field/blob/master/Cesium-3D-Wind/customParticleSystem.js).

However, you should be aware that ComputeCommands has better performance than DrawCommands for computation, because DrawCommands usually will be executed one time per frustum, which means it will result redundant computation.

**Comment by zouyaoji** [comment]
Thank you very much for your answer. 

I have read your post and hope that Cesium can adopt your proposal. Now I have another problem that I want to show the wind map of a certain area, such as latitude from 10 to 60 and longitude from 70 to 140. I found that I can modify the function particleOutbound in random.frag to control the latitude area, but the longitude range does not know how to control it better.

 It seems that I still have a lot to learn. Please forgive me for my poor English ability...

**Comment by zouyaoji** [comment]
I figured it out, thank you very much.

**Comment by zouyaoji** [comment]
![image](https://user-images.githubusercontent.com/24430116/56799639-e8423600-684b-11e9-8cf6-c72b023917d2.png)

**Comment by zouyaoji** [comment]
If you only want to see a partial area, you can modify the function particleOutbound in "random.frag.js" to be like this:
``` js
bool particleOutbound(vec4 particle) {
    // return particle.y < -90.0 || particle.y > 90.0;
    return particle.y < 10.0 || particle.y > 60.0 || particle.x < 70.0 || particle.x > 140.0;
}
```

**Comment by OldGong** [comment]
how to  replace all the ComputeCommands with DrawCommands ?

**Comment by RaymanNg** [comment]
I just refactor my demo, now it is able to be integrated with Cesium official code, feel free to check it.

PS: there is some performance loss since I can't use MRT in computeCommand, but I think it is acceptable.

**Comment by OldGong** [comment]
Thank you, you made me take a step closer to understanding of cesium.

**Comment by zouyaoji** [comment]
What does the color in DEMO mean?

**Comment by RaymanNg** [comment]
> What does the color in DEMO mean?

Different colors mean different wind speed, and this demo uses the color table "GMT_panoply" in [NCL Graphics](https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml)

PS: please open a new issue for a new question next time

**Comment by zouyaoji** [comment]
OK, Thank you so much
