### ISSUE TITLE
What do I need to do to use JSON data instead?

### ISSUE THREAD

**Issue by ankit-shibu** [RaymanNg/3D-Wind-Field#10]

**Comment by RaymanNg** [comment]
I suggest you convert your data from JSON to NetCDF V3 (only V3 is supported), because binary file formats are usually more compact than text-based formats. Take my demo.nc file as example, the equivalent JSON file is 10+ times larger than the nc file

If you really want to use JSON data directly, you can modify the source code in dataProcess.js, you may want to change the "loadNetCDF" function to "loadJSON"
