### ISSUE TITLE
Sry for my question ! :( but i need help

### ISSUE THREAD

**Issue by KavamiDev** [RaymanNg/3D-Wind-Field#22]
I would like to make sure that the wind does not continue outside the geographical limits

Do you have any idea ? 

sry to make a long discution about that but , i need :/ 
![wind_visual](https://user-images.githubusercontent.com/51117467/66305973-97159280-e911-11e9-9e5a-2fea7eb6f265.png)

**Comment by RaymanNg** [comment]
emmm......  I don't quite understand your question.

If you want to restrict the range of particles, you can modify the viewerParameters.lonRange and viewerParameters.latRange variables and call the "applyViewerParameters" function

If you are talking about the particles random reset, increase the dropRate in the panel may help

**Comment by KavamiDev** [comment]
hummm ... Sorry I try to explain more my situation . 

I have to visualise a wind file , in one geograpic zone. I can do that , but now the probleme is , wind continue to display behind my delimitation 

""you can modify the viewerParameters.lonRange and viewerParameters.latRange  "" , i make that to have the delimitation of my geographic zone.

And if i increase the dropRate in the panel , wind can't stay fluid . 

I need to have a separation like that 
![wind_visual_forum](https://user-images.githubusercontent.com/51117467/66453841-cd205700-ea76-11e9-91fe-ad0611ffd92e.png)


On the left the wind i need , and on the right , i need to 'hide' the wind . 


Thanks for your reply , if you are interest I can give you my code when i'm finish
Have a good day

**Comment by RaymanNg** [comment]
I think you can modify the GLSL code in postProcessingPosition.frag, there is a funtion named particleOutbound, and the vec3 variable particle corresponds to (lat, lon, height)

**Comment by hongbinzhang** [comment]
Hi KevinSTCK, I have the same problem as you, can you give me some code for reference? Thank you very much!  zhanghongbin.cn@gmail.com

**Comment by KavamiDev** [comment]
In postProcessingPosition.frag, in the folder glsl , you have a line, particleOutBound , and you have to change this value like you need. 
I make this 

bool particleOutbound(vec3 particle) {
    return particle.x < lonRange.x || particle.x > lonRange.y;
}

bool particleOutbounde(vec3 particle) {
    return particle.y < latRange.x || particle.y > latRange.y;
}

**Comment by hongbinzhang** [comment]
Ok, I see. Thank you !

**Comment by StarkZhou** [comment]
I have a  question about the wind ,that if i modify the shader,would can  i  draw the profile wind?
this project is draw a horizontal wind,and can select the height,if i chang the code to draw a profile wind in a lon or lat ,would it can make it in Cesium. 
last question ,my eventual aim is to draw a cloud in cesium which can fly dynamic due to the data of nv of wind,Is it possible in theory？

the question above which control the range of wind is solved by modify the shader in your code by myself.
my english is poor ,please tell me the answer. thank you very much.



sorry  it is the data of nc of wind,which is wrf output data. my edit mistake
